# Permalinks
permalink:           pretty

# Setup
title:               Szko≈Ça IF
description:         ""
email:               filipczaplicki@gmail.com
baseurl:             "/"
url:                 "https://inwitofitka.club"
paginate:            5

# number of tournaments on list
ntours:              12

# Custom vars

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - deploy.sh
